DROP DATABASE IF EXISTS movierentals;
DROP USER IF EXISTS `movie_svc`@`%`;
CREATE DATABASE IF NOT EXISTS movierentals CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `movie_svc`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `beerservice`.* TO `movie_svc`@`%`;
FLUSH PRIVILEGES;